dataset:
    col_data : ['data']
    col_categorical_prov : ['codice_regione', 'denominazione_regione','codice_provincia', 'denominazione_provincia']
    col_numerical_prov   : ['nuovi_casi']
    col_categorical_reg : ['codice_regione',  'denominazione_regione']
    col_numerical_reg   : ['ricoverati_con_sintomi', 'terapia_intensiva', 'totale_ospedalizzati', 'dimessi_guariti', 'deceduti', 'tamponi']
    ordering : ['data','codice_regione','codice_provincia']
    numerical: ['ricoverati_con_sintomi', 'terapia_intensiva', 'totale_ospedalizzati', 'dimessi_guariti', 'deceduti', 'tamponi', 'popolazione', 'nuovi_casi']
    merge: ['data', 'codice_regione', 'denominazione_regione']
    target: ['nuovi_casi']
    aggregate: True

setting:
    batch_size: 128
    past_step: 20
    future_step: 10

model:
    categorical: [21, 112]
    num_layer_gnn : 2
    out_preprocess : 256
    dropout : 0.15
    hidden_propagation : 128
    concat : True
    embedding : True
    dim_categorical : 128
    
grid_search:
    num_layer_gnn : [1,2,4,8]
    out_preprocess : [64, 128, 256]
    dropout : [0.05,0.1,0.15]
    hidden_propagation : [64, 128, 256]
    embedding : [True, False]
    concat : [True, False]
    dim_categorical : [64, 128, 256]
    
paths:
    popolazione: '/home/andrea/Scrivania/Tesi/leonardo/data/popolazione.csv'
    data: '/home/andrea/Scrivania/Tesi/leonardo/data'
    adj: '/home/andrea/Scrivania/Tesi/leonardo/data/adj'
    dati-province: '/home/andrea/Scrivania/Tesi/leonardo/data/dati-province'
    dati-regioni: '/home/andrea/Scrivania/Tesi/leonardo/data/dati-regioni'
    models: '/home/andrea/Scrivania/Tesi/leonardo/best_models'
    fig: '/home/andrea/Scrivania/Tesi/leonardo/figures'