dataset:
    col_data : ['data']
    col_categorical_prov : ['codice_regione', 'codice_provincia']
    col_numerical_prov   : ['nuovi_casi']
    col_categorical_reg : ['codice_regione']
    col_numerical_reg   : ['ricoverati_con_sintomi', 'terapia_intensiva', 'totale_ospedalizzati', 'dimessi_guariti', 'deceduti']
    ordering : ['data','codice_regione','codice_provincia']
    numerical: ['ricoverati_con_sintomi', 'terapia_intensiva', 'totale_ospedalizzati', 'dimessi_guariti', 'deceduti', 'nuovi_casi']
    merge: ['data', 'codice_regione', 'denominazione_regione']
    target: ['nuovi_casi']
    aggregate: True

setting:
    batch_size: 128
    past_step: 30
    future_step: 50
    in_feat: 12

model:
    categorical: [21, 112, 4, 12, 31]
    num_layer_gnn : 2
    out_preprocess : 256
    dropout : 0.15
    hidden_propagation : 128
    concat : True
    embedding : True
    dim_categorical : 128

    
paths:
    popolazione: '/home/andrea/Scrivania/Tesi/leonardo/data/popolazione.csv'
    data: '/home/andrea/Scrivania/Tesi/leonardo/data/dataset'
    raw_data: '/home/andrea/Scrivania/Tesi/leonardo/data/raw_data'
    adj: '/home/andrea/Scrivania/Tesi/leonardo/data/adj'
    models: '/home/andrea/Scrivania/Tesi/leonardo/best_models'
    config: '/home/andrea/Scrivania/Tesi/leonardo/config'
    list_models : '/home/andrea/Scrivania/Tesi/leonardo/models'
    fig: '/home/andrea/Scrivania/Tesi/leonardo/figures'
    fig_flows: '/home/andrea/Scrivania/Tesi/leonardo/figures/covid/flows'