setting:
    dataset: 'covid'
    name_model: ''
    train: True
    past_step : 30
    future_step : 10
    lr : 1e-4
    weight_decay : 4e-3
    epochs : 2500
    plot: True

loss_function:
    alpha : 20
    beta: 1.5
    gamma: 1e-2
    delta: 6

dataset:
    train_split : 0.7
    val_split : 0.1
    in_feat_past : 10
    in_feat_future : 7
    
categorical:
    covid: 
       past: [21, 112, 4, 12, 31, 7, 2]
       future: [21, 112, 4, 12, 31, 7, 2]
       
    telephone: [43, 1, 1, 30, 3, 24]

paths:
    data: '/home/x2030admin/andrea/diffusion/data/dataset'
    adj: '/home/x2030admin/andrea/diffusion/data/adj'
    models: '/home/x2030admin/andrea/diffusion/best_models'
    fig: '/home/x2030admin/andrea/diffusion/figures'
    config: '/home/x2030admin/andrea/diffusion/config'
    list_models : '/home/x2030admin/andrea/diffusion/models'
