setting:
    dataset: 'telephone'
    past_step : 30
    future_step : 50
    lr : 1e-4
    weight_decay : 3e-4
    alpha : 7e-5
    epochs : 1
    in_feat: 7
    plot: False
    
categorical:
    covid: [21, 112, 4, 12, 31]
    telephone: [43, 1, 1, 30, 3, 24]

paths:
    data: '/home/andrea/Scrivania/Tesi/leonardo/data/dataset'
    adj: '/home/andrea/Scrivania/Tesi/leonardo/data/adj'
    models: '/home/andrea/Scrivania/Tesi/leonardo/best_models'
    config: '/home/andrea/Scrivania/Tesi/leonardo/config'
    list_models : '/home/andrea/Scrivania/Tesi/leonardo/models'
    fig: '/home/andrea/Scrivania/Tesi/leonardo/figures'