setting:
    dataset: 'telephone'
    past_step : 30
    future_step : 50
    lr : 1e-4
    weight_decay : 3e-4
    alpha : 7e-5
    epochs : 2000
    
categorical:
    covid: [21, 112, 4, 12, 31]
    telephone: [43, 1, 1, 30, 3, 24]

paths:
    popolazione: '/home/andrea/Scrivania/Tesi/leonardo/data/popolazione.csv'
    data: '/home/andrea/Scrivania/Tesi/leonardo/data/dataset'
    adj: '/home/andrea/Scrivania/Tesi/leonardo/data/adj'
    dati-province: '/home/andrea/Scrivania/Tesi/leonardo/data/raw_data/dati-province'
    dati-regioni: '/home/andrea/Scrivania/Tesi/leonardo/data/raw_data/dati-regioni'
    models: '/home/andrea/Scrivania/Tesi/leonardo/best_models'
    config: '/home/andrea/Scrivania/Tesi/leonardo/config'
    list_models : '/home/andrea/Scrivania/Tesi/leonardo/models'
    fig: '/home/andrea/Scrivania/Tesi/leonardo/figures'