setting:
    batch_size: 128
    past_step: 10
    future_step: 4

model:
    categorical: [21, 112]
    num_layer_gnn : 2
    out_preprocess : 256
    dropout : 0.15
    hidden_propagation : 128
    concat : True
    embedding : True
    dim_categorical : 128
    
grid_search:
    num_layer_gnn : [1,2,4,8]
    out_preprocess : [64, 128, 256]
    dropout : [0.05,0.1,0.15]
    hidden_propagation : [64, 128, 256]
    embedding : [True, False]
    concat : [True, False]
    dim_categorical : [64, 128, 256]
    
paths:
    popolazione: '/home/andrea/Scrivania/Tesi/leonardo/data/popolazione.csv'
    data: '/home/andrea/Scrivania/Tesi/leonardo/data'
    models: '/home/andrea/Scrivania/Tesi/leonardo/models'
    fig: '/home/andrea/Scrivania/Tesi/leonardo/figures/traffic/'